### PR TITLE
iOS rewrite with image effect

### PR DESCRIPTION
**Pull request by toots**
This is just an uncleaned preview to check with you guys if that solution would work for y'all.

I ended-up rewriting the camera preview rendering into a proper `GLKView`/`GLKViewController` so we can access the video frames and apply `CIFilter`.

It seems to be super fast and I believe that this'll be a great basis for more involved video stuff. However, the plugin logic still needs a lot of cleanup before it's mergeable..

### CODE REVIEW

**Comment by toots** [comment]
Ok, in the process of cleaning up the code, I realized that it was prolly better to start from scratch. All the image capture logic doesn't have to be bound to a view. 

I've created a `CameraSessionManager` class to handle all session operations. It is there that capturing full image should take place. For preview image, `GLKView` has a nice `snapshot` method that will do the trick.

Likewise, `hide`/`show` plugin logic can be pushed down to the `GTKView`.

The current PR has the basic functionalities that I need for my app. I can finish wiring up the remaining plugin functionalities if you guys are cool with this rewrite.

**Comment by mbppower** [comment]
That would be really great! I was looking for way to rewrite the code for take the preview snapshot without the view workaround. That's the case for Android as well, which has the same approach.

**Comment by toots** [comment]
Sweet. I'm almost done with implementing the plugin features. I'm confused about one tho: does `takePicture` have to save to disk or is it just intended to pass back to the registered callback?

**Comment by mbppower** [comment]
I was thinking in two options for it. 
First write the picture to disk and pass back the paths, like it's already implemented.
Second, because the picture could be very large to pass the bytes to the callback, would be create to insert a resize feature:

takePicture({picWidth: 200, picHeight: 200}, ResultType.BYTES)
takePicture({picWidth: 200, picHeight: 200}, ResultType.PATHS)

And then the registered listener would receive the parameters based on the ResultType

What do you think?

**Comment by mbppower** [comment]
Hi toots, please tell me in what part are you working on. So I can help code what's missing.

**Comment by toots** [comment]
I'm almost done I'll push the final changes tonight.

**Comment by toots** [comment]
Actually I just did.. This fully functional and doesn't seem to crash. I'm not sure what to do with orientation so I've let that for you to decide. Otherwise, I think it is ready for review/merge.

**Comment by mbppower** [comment]
That's awesome, I'll test. Thanks.

**Comment by mbppower** [comment]
This is done. I've got some performance issues when running the preview on iPhone 4 though. I need to find a way to render all the transforms using the GPU through a texture 2d. Thanks for your work toots!

**Pull request closed without merging**
